package org.firstinspires.ftc.teamcode;

public enum AutonBase {
    HOOKDROP,
    MOVEBACK,
    STRAFERIGHT,
    STRAFELEFT,
    MOVEFORWARDSLOWLY,
    DROPMARKER,
    TURNRIGHT,
    TURNLEFT,
    TURNQUARTERRIGHT,
    TURNQUARTERLEFT,
    MOVEBACKSLOWLY,
    BALLKNOCKER
}